### PR TITLE
Add support for ScriptHookVDotNetCore

### PR DESCRIPTION
**Pull request by Sardelka9515**
Nothing need to be changed since it shares identical scripting API with SHVDN.

Works perfectly, at least in my testing

### CODE REVIEW

**Comment by justalemon** [comment]
GitHub is being stupid and is not allowing me to update the branch.

Please merge master onto the PR so it can actually try and build with .NET 7 on CI

**Comment by justalemon** [comment]
Turns out, I forgot to change the build .NET version. Whops.

Can you merge master again? Thanks!

**Comment by Sardelka9515** [comment]
No problem

**Comment by justalemon** [comment]
Looks like it copies the SHVDNCore DLL to the output directory. Could you please change that?

You could take a look at the SHVDN3 csproj if you are not sure how to do it :)

image

**Comment by justalemon** [comment]
Also, I don't think that the deps.json is required. That can be disabled with:

```xml
<GenerateDependencyFile>false</GenerateDependencyFile>
```

**Comment by Sardelka9515** [comment]
Done. Do i need to squash this to one commit?

**Comment by justalemon** [comment]
Sure

**Comment by justalemon** [comment]
Just letting you know: There is nothing wrong with this PR, I just want to do some stuff before I merge and release :)

**Comment by Sardelka9515** [comment]
Sure, no porblem 🙆‍♂️

**Comment by Sardelka9515** [comment]
Closing this to avoid confusion as SHVDNC might get merged into SHVDN itself in the future

**Comment by justalemon** [comment]
I have been following the issues on the SHVDN repo.

Can you keep this around while .NET Core support is fully implemented? So i can do some testing locally and prepare for the Core version.

**Comment by justalemon** [comment]
So, it was decided in scripthookvdotnet/scripthookvdotnet#1036 that Core/5+ support will not be added to the existing version of SHVDN.

@Sardelka9515 do you plan to keep working on the core version in your repo?

**Comment by Sardelka9515** [comment]
The core version can be maintained with minimum efforts (I can easily merge the the SHVDN upstream code at anytime) it currently have some issues with exception handling when running alongside SHVDN. it was resolved in [scripthookvdotnet#1167](https://github.com/scripthookvdotnet/scripthookvdotnet/pull/1167) but the new version is not released yet. Maybe kagikn will make another version for .NET Core in the future but SHVDNC should work fine for now

**Pull request merged**
