### PR TITLE
Added thread safe operations in ObjectPool

### LINKED ISSUE #44: "InvalidOperationException: Collection was modified" when executing ObjectPool.Remove
So I'm trying to remove a list of submenus to replace them with new ones and I'm getting this error. Sometimes also happens after adding submenus.

### PR DESCRIPTION
**Pull request by KimTisott**
Replaced the former internal type from List to ConcurrentDictionary, using the object's hash code as key.

This fixes #44 .

### CODE REVIEW

**Comment by justalemon** [comment]
I guess that the usage of a ConcurrentDictionary instead of a ConcurrentBag or ConcurrentQueue is because the later two don't have a Contains method, right?

**Comment by KimTisott** [comment]
Yes, Bag and Queue are very limited data types. Dictionary gives you more flexibility,

**Comment by KimTisott** [comment]
Since this is my first contribution, I only replaced the collection operations with dictionary's, and avoided changing the code too much.

After building a mod menu for myself, with about 50 menus and submenus, some with thousands of items, there is a noticeable loading time of 5~10 seconds. This change already allows lazy loading such as adding items on opening for example, thus reducing starting loading times.

I am specialized in microprocessing, performance analysis and code optimization, and could also improve most of the operations that you have, with your permission.

**Comment by justalemon** [comment]
Feel free to send PRs for anything you would like to fix. I have to test them a bit more than other projects due to some missing assemblies in the Mono implementation of the [CFX Framework](https://github.com/citizenfx/fivem) (FiveM, RedM and LibertyM).

**Comment by justalemon** [comment]
I have confirmed this work on FiveM.

**Pull request merged**
